{% set name = "qcelemental" %}
{% set version = "0.51.1" %}
{% set sha256 = "d92eec6b5e2b29df1bfb20f2d9e2299354d412503a5dea5e4cfbb3596e92e135" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - numpy
    - pint
    - pydantic >=2.11,<3
    - python >={{ python_min }}
  run_constrained:
    - qcmanybody >=0.7.1
    # - nglview >=4.0

test:
  imports:
    - qcelemental
  requires:
    - networkx >=2.4.0
    - nglview
      # networkx and nglview might be imposing a pyqt dependence on qcel for the c-f migrators
    - setuptools <82.0
      # nglview v4 avail for >=py311 but py310 nglview needs pkg_resources
    - pytest
    - scipy
    - pip
    - python {{ python_min }}
    - qcmanybody
  commands:
    - test -f $SP_DIR/qcelemental/__init__.py
    - pip check
    - python -c "import qcelemental as qc;assert qc.__version__ == '{{ version }}', f'{qc.__version__=} differs from recipe=\'{{ version }}\''"
    - pytest --pyargs qcelemental -k "not pubchem_multiout_g"

about:
  home: https://github.com/MolSSI/QCElemental
  dev_url: https://github.com/MolSSI/QCElemental
  doc_url: https://molssi.github.io/QCElemental/
  doc_source_url: https://github.com/MolSSI/QCElemental/blob/master/docs/source/index.rst
  license: BSD-3-Clause
  license_url: https://opensource.org/licenses/BSD-3-Clause
  license_file: LICENSE
  summary: QCElemental is a resource module for quantum chemistry containing physical constants and periodic table data from NIST and molecule handlers.

extra:
  recipe-maintainers:
    - loriab
    - dgasmith
    - lnaden
    - bennybp
